### ISSUE TITLE
repo太大了，clone好慢

### ISSUE THREAD

**Issue by zchrissirhcz** [Show-Me-the-Code/python#103]
git clone要100多兆，应该主要是图片吧，建议把图片都删掉，gitignore最好也配置下，过滤掉图片。

**Comment by defshine** [comment]
@Yixiaohan 
可以考虑改造成 使用readme 索引项目的形式，repo由个人维护即可～
特别是遇到github抽风的时候，clone确实比较头疼

**Comment by Yixiaohan** [comment]
@zchrissirhcz  @defshine  嗯，今天有时间的话，我就修改一下 :-)
