### ISSUE TITLE
How to make a loop for this

### ISSUE THREAD

**Issue by riszkyhermawan** [Show-Me-the-Code/python#370]
![IMG_20201017_154952.jpg](https://user-images.githubusercontent.com/71969296/96333020-b0f3c480-1091-11eb-9cae-713d1ffb25d7.jpg)

**Comment by Yash999-design** [comment]
#Is it giving you the desired output?

def month(balance):
    minimum_payment = balance*0.02
    unpiad_balance = balance - minimum_payment
    interest = (0.18/12.0) * unpiad_balance
    next_month_balance = unpiad_balance + interest
    return next_month_balance
    # print("Remaining Balance =", next_month_balance)

def result_printer():
    total = 0

    for i in range(12):
        if total == 0:
            value = int(input())
            total += month(value)
        else:
            output = month(total)
            total += output

    print("Remaining Balance = ", total)  

result_printer()

**Comment by Yash999-design** [comment]
""" 
I used month as function name instead of month1
"""

def month(balance):
    minimum_payment = balance*0.02
    unpiad_balance = balance - minimum_payment
    interest = (0.18/12.0) * unpiad_balance
    next_month_balance = unpiad_balance + interest
    return next_month_balance
    # print("Remaining Balance =", next_month_balance)

def result_printer():
    total = 0

    for i in range(12):
        if total == 0:
            value = int(input())
            total = month(value)
        else:
            output = month(total)
            total = output

    print("Remaining Balance = ", total)  

result_printer()

**Comment by Yash999-design** [comment]
`def month(balance):
    minimum_payment = balance*0.02
    unpiad_balance = balance - minimum_payment
    interest = (0.18/12.0) * unpiad_balance
    next_month_balance = unpiad_balance + interest
    return next_month_balance
    # print("Remaining Balance =", next_month_balance)

def result_printer():
    total = 0

    for i in range(12):
        if total == 0:
            value = int(input())
            total = month(value)
        else:
            output = month(total)
            total = output

    print("Remaining Balance = ", total)  

result_printer()`
